// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_user

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func UserDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"email": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 250),
				},
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"role": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type UserModel struct {
	Email types.String `tfsdk:"email"`
	Id    types.String `tfsdk:"id"`
	Name  types.String `tfsdk:"name"`
	Role  types.String `tfsdk:"role"`
}
