package resource_cloud_account

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// CloudAccountResourceSchema describes the tsuga_cloud_account resource.
func CloudAccountResourceSchema() schema.Schema {
	requiresReplaceObject := []planmodifier.Object{objectplanmodifier.RequiresReplace()}

	return schema.Schema{
		Description: "A cloud account (AWS or GCP) connected to Tsuga for inventory scanning. The trust relationship (IAM role or workload identity) must already exist on the cloud side before creating the account.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Identifier of the cloud account. Generated by Tsuga.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"cloud_type": schema.StringAttribute{
				Computed:    true,
				Description: "Cloud provider of the account, derived from the configured connection block.",
			},
			"cloud_account_id": schema.StringAttribute{
				Computed:    true,
				Description: "Cloud-native account identifier (AWS account ID or GCP project ID), derived from the configured connection block.",
			},
			"account_friendly_name": schema.StringAttribute{
				Optional:    true,
				Description: "Human-readable name for the account shown in Tsuga.",
			},
			"aws": schema.SingleNestedAttribute{
				Optional:      true,
				Description:   "AWS connection settings. Mutually exclusive with `gcp`. Immutable.",
				PlanModifiers: requiresReplaceObject,
				Attributes: map[string]schema.Attribute{
					"account_id": schema.StringAttribute{
						Required:    true,
						Description: "AWS account ID that Tsuga scans.",
					},
					"external_id": schema.StringAttribute{
						Required:    true,
						Description: "External ID Tsuga passes when assuming the cross-account IAM role.",
					},
					"role_arn": schema.StringAttribute{
						Required:    true,
						Description: "ARN of the IAM role Tsuga assumes to read inventory in the account.",
					},
				},
			},
			"gcp": schema.SingleNestedAttribute{
				Optional:      true,
				Description:   "GCP connection settings. Mutually exclusive with `aws`. Immutable.",
				PlanModifiers: requiresReplaceObject,
				Attributes: map[string]schema.Attribute{
					"project_id": schema.StringAttribute{
						Required:    true,
						Description: "GCP project ID that Tsuga scans.",
					},
					"service_account_id": schema.StringAttribute{
						Required:    true,
						Description: "Service account Tsuga impersonates to read inventory.",
					},
					"workload_identity_provider": schema.StringAttribute{
						Required:    true,
						Description: "Workload identity provider resource name used for federated authentication.",
					},
				},
			},
		},
	}
}

type CloudAccountModel struct {
	Id                  types.String      `tfsdk:"id"`
	CloudType           types.String      `tfsdk:"cloud_type"`
	CloudAccountId      types.String      `tfsdk:"cloud_account_id"`
	AccountFriendlyName types.String      `tfsdk:"account_friendly_name"`
	Aws                 *AwsSettingsModel `tfsdk:"aws"`
	Gcp                 *GcpSettingsModel `tfsdk:"gcp"`
}

type AwsSettingsModel struct {
	AccountId  types.String `tfsdk:"account_id"`
	ExternalId types.String `tfsdk:"external_id"`
	RoleArn    types.String `tfsdk:"role_arn"`
}

type GcpSettingsModel struct {
	ProjectId                types.String `tfsdk:"project_id"`
	ServiceAccountId         types.String `tfsdk:"service_account_id"`
	WorkloadIdentityProvider types.String `tfsdk:"workload_identity_provider"`
}
