// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_retention_policy

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RetentionPolicyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data_source": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"logs",
						"metrics",
						"traces",
					),
				},
			},
			"duration_days": schema.Int64Attribute{
				Required: true,
				Validators: []validator.Int64{
					int64validator.Between(1, 3650),
				},
			},
			"env": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 250),
				},
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"is_enabled": schema.BoolAttribute{
				Required: true,
			},
			"team_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 250),
				},
			},
		},
	}
}

type RetentionPolicyModel struct {
	DataSource   types.String `tfsdk:"data_source"`
	DurationDays types.Int64  `tfsdk:"duration_days"`
	Env          types.String `tfsdk:"env"`
	Id           types.String `tfsdk:"id"`
	IsEnabled    types.Bool   `tfsdk:"is_enabled"`
	TeamId       types.String `tfsdk:"team_id"`
}
