// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_custom_usage_tag

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CustomUsageTagResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the custom usage tag. Generated by Tsuga.",
				MarkdownDescription: "Unique identifier of the custom usage tag. Generated by Tsuga.",
			},
			"tag_key": schema.StringAttribute{
				Required:            true,
				Description:         "Telemetry tag key to track as a custom usage dimension. The key must be unique within the organization.",
				MarkdownDescription: "Telemetry tag key to track as a custom usage dimension. The key must be unique within the organization.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 250),
				},
			},
		},
	}
}

type CustomUsageTagModel struct {
	Id     types.String `tfsdk:"id"`
	TagKey types.String `tfsdk:"tag_key"`
}
